slides:
	pandoc singularity-doc-preamble.md SlurmAndSingularityTraining.md -o SlurmAndSingularityTraining.pdf -t beamer --slide-level=2 --pdf-engine=xelatex --pdf-engine-opt=-shell-escape
	pandoc singularity-doc-preamble.md AiCloudOverview.md -o AiCloudOverview.pdf -t beamer --slide-level=2 --pdf-engine=xelatex --pdf-engine-opt=-shell-escape
